Repository mindsdb/mindsdb_native, pull requests merged in 2020-11, with the labels that each got.

#262 Enable snowflake tests
  .github/workflows/mindsdb_native.yml
  tests/integration_tests/data_sources/__init__.py
  tests/integration_tests/data_sources/test_clickhouse_ds.py
  tests/integration_tests/data_sources/test_snowflake_ds.py
Labels: dependencies, test

#267 Alias for numerical categorical columns
  mindsdb_native/libs/constants/mindsdb.py
  mindsdb_native/libs/phases/data_analyzer/data_analyzer.py
  mindsdb_native/libs/phases/type_deductor/type_deductor.py
  tests/unit_tests/libs/phases/data_analyzer/test_data_analyzer.py
  tests/unit_tests/libs/phases/data_cleaner/test_data_cleaner.py
Labels: refactor

#265 Test with broken datasets
  mindsdb_native/libs/data_sources/gcs_ds.py
  mindsdb_native/libs/data_sources/s3_ds.py
  mindsdb_native/libs/data_types/data_source.py
  mindsdb_native/libs/phases/data_extractor/data_extractor.py
  tests/integration_tests/data_sources/__init__.py
  tests/integration_tests/data_sources/test_clickhouse_ds.py
  tests/integration_tests/data_sources/test_maria_ds.py
  tests/integration_tests/data_sources/test_mongodb_ds.py
  tests/integration_tests/data_sources/test_ms_sql_ds.py
  tests/integration_tests/data_sources/test_mysql_ds.py
  tests/integration_tests/data_sources/test_postgres_ds.py
  tests/integration_tests/data_sources/test_snowflake_ds.py
  tests/unit_tests/utils.py
Labels: test

#268 Quicklearn improvements
  mindsdb_native/libs/backends/lightwood.py
  mindsdb_native/libs/controllers/transaction.py
  mindsdb_native/libs/phases/data_transformer/data_transformer.py
Labels: bug, enhancement

#266 Dont allow <= 10 rows for learning
  mindsdb_native/libs/phases/data_cleaner/data_cleaner.py
  mindsdb_native/libs/phases/data_extractor/data_extractor.py
  tests/unit_tests/libs/phases/data_cleaner/test_data_cleaner.py
Labels: bug

#273 Fix word distribution
  mindsdb_native/libs/helpers/text_helpers.py
Labels: bug

#274 ignore useless columns
  mindsdb_native/libs/phases/data_cleaner/data_cleaner.py
Labels: bug, enhancement

#271 remove confidence variation analysis
  mindsdb_native/libs/controllers/predictor.py
  mindsdb_native/libs/controllers/transaction.py
  tests/unit_tests/libs/controllers/test_predictor.py
Labels: refactor

#295 Lazy and filter-able
  mindsdb_native/libs/controllers/functional.py
  mindsdb_native/libs/controllers/predictor.py
  mindsdb_native/libs/data_sources/aws_athena_ds.py
  mindsdb_native/libs/data_sources/clickhouse_ds.py
  mindsdb_native/libs/data_sources/file_ds.py
  mindsdb_native/libs/data_sources/gcs_ds.py
  mindsdb_native/libs/data_sources/maria_ds.py
  mindsdb_native/libs/data_sources/mongodb_ds.py
  mindsdb_native/libs/data_sources/ms_sql_ds.py
  mindsdb_native/libs/data_sources/mysql_ds.py
  mindsdb_native/libs/data_sources/postgres_ds.py
  mindsdb_native/libs/data_sources/redshift_ds.py
  mindsdb_native/libs/data_sources/s3_ds.py
  mindsdb_native/libs/data_sources/snowflake_ds.py
  mindsdb_native/libs/data_types/data_source.py
  requirements.txt
  tests/integration_tests/data_sources/test_clickhouse_ds.py
  tests/integration_tests/data_sources/test_maria_ds.py
  tests/integration_tests/data_sources/test_mongodb_ds.py
  tests/integration_tests/data_sources/test_mysql_ds.py
  tests/integration_tests/data_sources/test_postgres_ds.py
  tests/unit_tests/libs/controllers/test_predictor.py
Labels: enhancement, refactor

#303 Improvement to what will no longer be telemetry
  mindsdb_native/__init__.py
  mindsdb_native/libs/controllers/functional.py
  mindsdb_native/libs/controllers/predictor.py
  mindsdb_native/libs/data_types/mindsdb_logger.py
  mindsdb_native/libs/helpers/general_helpers.py
  requirements.txt
  tests/integration_tests/flows/quick_interface.py
  tests/unit_tests/libs/controllers/test_predictor.py
Labels: enhancement, refactor

#301 Test with broken datasets
  tests/integration_tests/test_broken_datasets.py
Labels: test

#305 issue-296
  mindsdb_native/libs/controllers/transaction.py
  mindsdb_native/libs/data_types/data_source.py
  tests/unit_tests/libs/controllers/test_predictor.py
Labels: bug

#307 Refactor datasources
  mindsdb_native/libs/data_sources/aws_athena_ds.py
  mindsdb_native/libs/data_sources/clickhouse_ds.py
  mindsdb_native/libs/data_sources/file_ds.py
  mindsdb_native/libs/data_sources/gcs_ds.py
  mindsdb_native/libs/data_sources/maria_ds.py
  mindsdb_native/libs/data_sources/mongodb_ds.py
  mindsdb_native/libs/data_sources/ms_sql_ds.py
  mindsdb_native/libs/data_sources/mysql_ds.py
  mindsdb_native/libs/data_sources/postgres_ds.py
  mindsdb_native/libs/data_sources/redshift_ds.py
  mindsdb_native/libs/data_sources/s3_ds.py
  mindsdb_native/libs/data_sources/snowflake_ds.py
  mindsdb_native/libs/data_types/data_source.py
  mindsdb_native/libs/helpers/multi_data_source.py
  tests/integration_tests/data_sources/test_clickhouse_ds.py
  tests/integration_tests/data_sources/test_maria_ds.py
  tests/integration_tests/data_sources/test_mongodb_ds.py
  tests/integration_tests/data_sources/test_mysql_ds.py
  tests/integration_tests/data_sources/test_postgres_ds.py
Labels: refactor
