Repository mindsdb/mindsdb_native, pull requests merged in 2020-10, with the labels that each got.

#191 Best mixer selection
  mindsdb_native/libs/backends/lightwood.py
  mindsdb_native/libs/controllers/predictor.py
  mindsdb_native/libs/phases/model_analyzer/model_analyzer.py
Labels: enhancement

#200 Identifier detection improvements
  mindsdb_native/libs/helpers/text_helpers.py
  mindsdb_native/libs/phases/type_deductor/type_deductor.py
  tests/unit_tests/libs/controllers/test_predictor.py
  tests/unit_tests/libs/helpers/test_text_helpers.py
Labels: enhancement, refactor

#205 Improve history query generation
  mindsdb_native/libs/helpers/query_composer.py
  tests/unit_tests/libs/helpers/test_query_composer.py
Labels: bug, enhancement

#212 Snowflake tests
  mindsdb_native/__init__.py
  mindsdb_native/libs/data_sources/snowflake_ds.py
  tests/integration_tests/data_sources/test_snowflake_ds.py
Labels: bug, test

#230 added columns key
  mindsdb_native/libs/phases/type_deductor/type_deductor.py
  tests/unit_tests/libs/controllers/test_predictor.py
  tests/unit_tests/libs/phases/type_deductor/test_type_deductor.py
Labels: enhancement

#226 Auto increment detection fix
  mindsdb_native/libs/helpers/text_helpers.py
  tests/unit_tests/libs/helpers/test_text_helpers.py
Labels: enhancement

#233 Added Redshift Datasource
  mindsdb_native/__init__.py
  mindsdb_native/libs/data_sources/redshift_ds.py
Labels: enhancement

#242 Flag for using database history
  .github/workflows/mindsdb_native.yml
  mindsdb_native/libs/backends/lightwood.py
  mindsdb_native/libs/controllers/predictor.py
  mindsdb_native/libs/helpers/query_composer.py
  mindsdb_native/libs/phases/data_extractor/data_extractor.py
  mindsdb_native/libs/phases/data_splitter/data_splitter.py
  requirements.txt
  tests/integration_tests/timeseries/database_history.py
  tests/unit_tests/libs/controllers/test_predictor_timeseries.py
  tests/unit_tests/utils.py
Labels: bug, enhancement, refactor, test

#249 Adding google cloud storage datasource
  mindsdb_native/libs/data_sources/gcs_ds.py
  optional_requirements_extra_data_sources.txt
Labels: dependencies, enhancement

#256 Hotfix for lzma torch dependency
  mindsdb_native/__about__.py
  requirements.txt
Labels: enhancement
