Repository mindsdb/mindsdb_native, pull requests merged in 2021-02, with the labels that each got.

#423 More accurate stop training
  mindsdb_native/libs/controllers/predictor.py
  mindsdb_native/libs/phases/model_interface/lightwood_backend.py
Labels: bug, refactor

#426 Only compute KNN when len(data) >= 2
  mindsdb_native/libs/phases/data_analyzer/data_analyzer.py
Labels: bug

#432 Unnest jsons
  mindsdb_native/libs/controllers/predictor.py
  mindsdb_native/libs/data_sources/file_ds.py
  mindsdb_native/libs/phases/data_extractor/data_extractor.py
  tests/integration_tests/nested/__init__.py
  tests/integration_tests/nested/test_nested_dataset.py
Labels: enhancement

#429 Handle -inf/inf values
  mindsdb_native/libs/phases/data_extractor/data_extractor.py
  tests/unit_tests/libs/phases/data_extractor/test_data_extractor.py
Labels: bug

#436 Boosted absolute error for confidence in regression tasks
  mindsdb_native/libs/helpers/conformal_helpers.py
  mindsdb_native/libs/phases/model_analyzer/model_analyzer.py
Labels: bug

#448 skip ignored columns in for loop
  mindsdb_native/libs/phases/data_analyzer/data_analyzer.py
Labels: bug

#447 get_nr_procs() should always return 1 for windows
  mindsdb_native/libs/helpers/mp_helpers.py
Labels: bug
