Repository mindsdb/mindsdb_native, pull requests merged in 2021-01, with the labels that each got.

#379 Remove multiprocess usage for small timeseries dataframes
  mindsdb_native/libs/controllers/transaction.py
  mindsdb_native/libs/phases/model_interface/lightwood_backend.py
Labels: bug

#380 Separate model per group by
  mindsdb_native/libs/controllers/functional.py
  mindsdb_native/libs/controllers/predictor.py
  mindsdb_native/libs/controllers/transaction.py
  mindsdb_native/libs/phases/model_analyzer/model_analyzer.py
  mindsdb_native/libs/phases/model_interface/lightwood_backend.py
  tests/unit_tests/libs/controllers/test_predictor_timeseries.py
Labels: Clickhouse timeseries

#371 add timeseries unit test
  mindsdb_native/libs/phases/model_interface/lightwood_backend.py
  tests/unit_tests/libs/controllers/test_predictor_timeseries.py
Labels: test

#399 Removed model listing
  mindsdb_native/libs/controllers/functional.py
  tests/unit_tests/libs/controllers/test_predictor.py
  tests/unit_tests/libs/controllers/test_predictor_timeseries.py
Labels: refactor

#403 Broken columns & column importance disabling
  mindsdb_native/config/__init__.py
  mindsdb_native/libs/controllers/transaction.py
  mindsdb_native/libs/phases/type_deductor/type_deductor.py
Labels: bug, refactor
